# Generated by Django 5.0.1 on 2024-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('pais', models.TextField()),
                ('estado', models.TextField()),
                ('cidade', models.TextField()),
            ],
        ),
    ]
