# Generated by Django 5.0.1 on 2024-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
